language: python
python:
  - "2.6"
  - "2.7"
before_script:
  - chmod +x ./.scripts/deploy.sh
install:
  - "pip install -r requirements.txt"
script:
  - nosetests
after_success:
  - ./.scripts/deploy.sh
